# .github/workflows/deploy-backend.yml

# Nome do workflow que aparecerá no GitHub Actions
name: Deploy Backend

# Gatilho: Este workflow roda automaticamente em qualquer push para a branch 'main'
on:
  push:
    branches:
      - main

# Define o job (tarefa) que será executado
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: lume-cume

      - name: Create Firebase Service Account File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > ./backend/firebase-service-account.json
        shell: bash

      - name: Build and Push Docker image
        run: |
          gcloud builds submit ./backend \
            --tag gcr.io/lume-cume/backend-api \
            --project=lume-cume

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-api \
            --image gcr.io/lume-cume/backend-api \
            --region southamerica-east1 \
            --platform managed \
            --allow-unauthenticated \
            --project=lume-cume