# .github/workflows/firebase-hosting-pull-request.yml
name: Deploy to Firebase Hosting on PR

on: pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Adicionado passo para criar o .env para builds de PR
      - name: Create .env file for Frontend PR
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_URL }}" > ./frontend/.env.production
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> ./frontend/.env.production
        shell: bash

      - name: Install and Build Frontend
        run: npm ci && npm run build
        working-directory: ./frontend
        
      - name: Deploy to Firebase Hosting Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUME_CUME }}'
          projectId: lume-cume
